######################## default configuration ####################
baseURL: /
title: jublaost-mitbestimmen
theme: hugo-theme-copper
paginate: 6
summaryLength: 10
appinsights_instrumentationkey: "16cafa35-2130-46e1-8055-06498a8476d8"
defaultContentLanguage: de
disableLanguages:
  - en # desable language from here
outputs:
  home:
    - HTML
    - RSS
markup:
  goldmark:
    renderer:
      unsafe: true